Testing Enumerables
ricardomonte/enumerables pull request #3
Opened 2020-10-09 23:47 UTC by ricardomonte

In this project we:

- Use Rspec to test all of the methods in Enumerables 
- Apply different tests for each method

2020-10-10 01:46 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far guys :clap: :clap: :clap: :clap: :clap:, but you still have just some minor changes :hammer: :wrench: :toolbox: to take care of.

- [ ] add test cases for multiply_els.

### Please make sure that you have worked on all the requirements before you submit another code review.
## Happy Coding :tophat:

2020-10-10 01:46 UTC, elmejdki commented on spec/enumerable_spec.rb
> +        expect(array.my_each { |num| puts num }).to eq(array.each { |num| puts num })
remove puts from the block giving to my_each and each.

2020-10-10 01:46 UTC, elmejdki commented on README.md
> +    - from that folder open the terminal.
add another line that said that the user should run bundle install.

2020-10-12 17:06 UTC, euqueme requested changes
> ### Pull Request reviewed by Maria Eugenia Queme P. (TSE)

### Hello @ricardomonte and @edxco :lollipop: :balloon: 

### Thank you for doing the changes requested by the previous reviewer :medal_sports: :medal_sports:  you've added several scenarios and your test cases have meaningful descriptions there are still mandatory changes so let's address them :construction: :construction_worker: :construction_worker: 

#### Project specific

- [ ] You should have one `it` block for each expected behaviour. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/itblock.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/))

> you seem to have positive and negative expected behaviors within the same `it` block, this is not correct each `it` block should contain one expected behavior, please separate them and use negative descriptions for the negative expected behaviors for example the negative of this it block 'Returns a new array with the results of running block once for every element in the collection.' could be "it doesn't return the original array when running a block once for every element in the collection."

### That's it, team! :raised_hands: 

### Please :pray: do the changes :technologist: :technologist: and submit back for a code review when you are done :memo: 

### Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-10-12 18:01 UTC, kubilaycaglayan approved these changes
Hello Team :wave: 
Status: Project Approved :green_circle: 

Thanks for making the required changes :+1: :blush: 

With all my respect :pray:

2020-10-13 06:27 UTC, merged